
name: DEPLOYMENT

on:
   workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: [12.x]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node-version }}
            - run: npm install
            - uses: akhileshns/heroku-deploy@v3.3.6
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: ${{secrets.APP_NAME}}
                  heroku_email: ${{secrets.EMAIL}}
                  procfile: "web: npm run start"
